### ISSUE TITLE
Can you provide ionic-native?

### ISSUE THREAD

**Issue by Anberm** [liugogal/cordova-plugin-baidu-ocr#1]

**Comment by Anberm** [comment]
such as:
`

@Plugin({
  pluginName: 'BaiduOcr',
  plugin: 'cordova-plugin-baidu-ocr', // npm package name, example: cordova-plugin-camera
  pluginRef: 'BaiduOcr', // the variable reference to call the plugin, example: navigator.geolocation
  repo: 'https://github.com/liugogal/cordova-plugin-baidu-ocr', // the github repository URL for the plugin
  install: 'cordova plugin add cordova-plugin-baidu-ocr', // OPTIONAL install command, in case the plugin requires variables
  installVariables: [], // OPTIONAL the plugin requires variables
  platforms: ['Android', 'iOS'] // Array of platforms supported, example: ['Android', 'iOS']
})
@Injectable()
export class BaiduOcr extends IonicNativePlugin {

  @Cordova()
  init(): Promise<any> {
    return; // We add return; here to avoid any IDE / Compiler errors
  }

  @Cordova()
  scanId(options?:any): Promise<any> {
    return; // We add return; here to avoid any IDE / Compiler errors
  }

  @Cordova()
  destroy(): Promise<any> {
    return; // We add return; here to avoid any IDE / Compiler errors
  }

}
`

**Comment by liugogal** [comment]
Ok !
ionic-native:

https://www.npmjs.com/package/@liu-gogal/baidu-ocr

**Comment by sumansuhag** [comment]
Hi!
Dear Sir I think

Instead of Promise-based methods, use RxJS Observables. This allows real-time streaming and cancellation during OCR, to improve the user experience in complex processes, like progressive scanning.

Add detailed TypeScript interfaces for all input options and output responses. This supports IntelliSense and validation when compiling Ionic/Angular projects.

Create thorough native-to-JS error mapping and retry systems that automatically manage temporary platform or camera errors.

Include customizable hooks for pre-processing images (like auto-cropping or marking OCR areas) driven by Ionic Framework UI parts.

Package the Ionic Native plugin with an Angular service layer that allows dependency injection, saves configuration states, and caches OCR results for offline use, improving reliability when the network is weak.

Release and document the package with usage examples showing complex applications, like batch scanning or adding support for cloud-based OCR tools.

This change brings the Baidu OCR Ionic Native experience up to date, encourages reactive architecture, and greatly increases developer speed and app reliability.
